In [1]:
f = open("c:/테스트폴더/새파일.txt", "r")
lines = f.readlines()
f.close()
print(lines)


['abc\n', 'def\n', 'ghj']


In [6]:
f = open("c:/테스트폴더/새파일.txt", "r")
lines = f.readlines()
f.close()
print(lines)
refined_list = []
for item in lines:
    refined_list.append(item.replace("\n", ""))
print(refined_list)

['abc\n', 'def\n', 'ghj']
['abc', 'def', 'ghj']


In [11]:
f = open("c:/테스트폴더/새파일.txt", "r")
page = f.read()
f.close()
print(page)
#['abc', 'def', 'ghj']
refined_list = page.split("\n")
print(refined_list)

abc
def
ghj
['abc', 'def', 'ghj']


In [13]:
f = open("c:/테스트폴더/새파일.txt", "a")
f.write("ㅋㅋㅋ")
f.close()

In [14]:
with open("c:/테스트폴더/새파일.txt", "a") as f:
    f.write("ㅎㅎㅎ")

In [18]:
class FourCal:
    def setdata(self, a, b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
aCal = FourCal()
bCal = FourCal()
aCal.setdata(4, 2)
print(aCal.add())
bCal.setdata(3, 8)
print(bCal.add())

6
11


In [19]:
class FourCal:
    def __init__(self, a, b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
aCal = FourCal(4, 2)
bCal = FourCal(3, 8)
print(aCal.add())
print(bCal.add())



6
11


In [21]:
class FourCal:
    def __init__(self, a, b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result

class MoreFourCal(FourCal):
    def pow(self):
        result = self.first**self.second
        return result

c = MoreFourCal(4, 2)
d = c.pow()
print(d)



16


In [24]:
class FourCal:
    def __init__(self, a, b):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
    def div(self):
        result = self.first / self.second
        return result

class MoreFourCal(FourCal):
    def pow(self):
        result = self.first**self.second
        return result
    def div(self):
        if self.second == 0:
            self.second = 0.00000000000000001
        result = self.first/self.second
        return result
    
c = MoreFourCal(4, 0)
d = c.div()
print(d)


4e+17


In [25]:
class MyMath:
    MyPI = 3.14
    
mm = MyMath()
print(mm.MyPI)

3.14


In [26]:
class MyMath:
    MyPI = 3.14
    
mm1 = MyMath()
mm1.MyPI = 4
mm2 = MyMath()
print(mm1.MyPI, mm2.MyPI)

4 3.14


In [33]:
import mod1
print(mod1.add_mod1(3, 4))
print(mod1.sub_mod1(3, 4))

7
-1


In [36]:
import mod1 as m1
print(m1.add_mod1(3, 4))
print(m1.sub_mod1(3, 4))

7
-1


In [34]:
from mod1 import add_mod1, sub_mod1
print(add_mod1(3, 4))
print(sub_mod1(3, 4))

7
-1


In [35]:
from mod1 import *       #전체를 가져올때 *
print(add_mod1(3, 4))
print(sub_mod1(3, 4))

7
-1


In [2]:
import mod2
print(mod2.add_mod2(3, 4))
print(mod2.PI)
mm2 = mod2.Math_mod2()
print(mm2.solve(2))

7
3.14
12.56


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [44]:
try:
    print(4/0)
except ZeroDivisionError as e:
    print(4/0.0000000000000000001)
    #print(e)
except

4e+19


In [45]:
def positive(l):             #이름을 잘 지어야함
    result=[]
    for i in l:
        if i > 0: result.append(i)
    return result

print(positive([1, -3, 2, 0, -5, 6]))

[1, 2, 6]


In [46]:
def positive(x):
    return x > 0
data = [1, -3, 2, 0, -5, 6]              #필터할것 데이터 지정
f = filter(positive, data)               #filter(필터이름, 데이터)
print(list(f))

[1, 2, 6]


lambda: 함수 형태로 하지 않아도 됨.(간편) filter 와 잘 어울림. 이름 안지어도 됨

In [47]:
data = [1, -3, 2, 0, -5, 6]
list(filter(lambda x: x>0, data))

[1, 2, 6]

In [51]:
a = int(input("숫자를 입력하세요"))
a = a + 1
print(a)

숫자를 입력하세요10
11


In [6]:
a, b = input("숫자 두개를 입력하세요").split()
a = int(a)
b = int(b)
print(a+1,"그리고", b+1)

숫자 두개를 입력하세요10 20
11 그리고 21


map: 넣었다 뺐다하는 번거러움 없애줌(간편)

In [8]:
a, b, c, d, e = map(int, input("숫자 5개를 입력하세요").split())
print(a+1,b+1, c+1, d+1, e+1)

숫자 5개를 입력하세요1 2 3 4 5
2 3 4 5 6


zip: 동일 개수로이루어진 자료형을 묶어주는 역할하는 함수

In [9]:
data1 = [1, 2, 3]
data2 = [4, 5, 6]
list(zip(data1, data2))

[(1, 4), (2, 5), (3, 6)]

In [10]:
data1 = [1, 2, 3]
data2 = [4, 5, 6]zip: 동일 개수로이루어진 자료형을 묶어주는 역할하는 함수
data3 = [7, 8, 9]
list(zip(data1, data2, data3))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

OS:  환경변수나 디렉터리, 파일 등의 os자원을 제어할 수 있게해주는 모듈

In [12]:
OS:  환경변수나 디렉터리, 파일 등의 os자원을 제어할 수 있게해주는 모듈import os
os.environ["path"]

'C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\W

In [13]:
os.getcwd()

'C:\\Users\\CPB06GameN'

glob: 디렉터리에 있는 파일들 리스트로 만들기

In [17]:
import glob
glob.glob('C:\\Users\\CPB06GameN\\*.py')
#*.py로 된것만 다 가져옴
#*.*하면 다 가져와짐

['C:\\Users\\CPB06GameN\\mod1.py', 'C:\\Users\\CPB06GameN\\mod2.py']

In [19]:
import time
time.time()

1622012760.0656133

In [20]:
time.time()

1622012765.9782155

In [21]:
time.time()

1622012839.1789591

In [23]:
time.localtime(time.time())

time.struct_time(tm_year=2021, tm_mon=5, tm_mday=26, tm_hour=16, tm_min=8, tm_sec=10, tm_wday=2, tm_yday=146, tm_isdst=0)

In [25]:
time.asctime(time.localtime(time.time())).split()

['Wed', 'May', '26', '16:09:28', '2021']

In [26]:
for i in range(10):
    print(i)
    time.sleep(1)

0
1
2
3
4
5
6
7
8
9


In [29]:
import random
random.random()

0.4600703236694026

In [34]:
random.randint(1, 45)

42

In [35]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for i in range(10): my_arr2=my_arr*2

Wall time: 15.6 ms


In [36]:
%time for i in range(10): my_list2=[x *2 for x in my_list]

Wall time: 793 ms


In [37]:
793/15.6

50.833333333333336

In [40]:
data = np.random.randn(2, 3)
data

array([[ 0.09124048, -0.64456649, -0.27410704],
       [-0.6688173 ,  1.85644938,  0.53689741]])

In [39]:
data * 10

array([[ -6.20949492,  -8.40708571,   7.0323976 ],
       [ 22.31456542, -11.03555622,  -1.93449041]])

In [41]:
data + data

array([[ 0.18248095, -1.28913297, -0.54821407],
       [-1.3376346 ,  3.71289877,  1.07379482]])

In [42]:
data.shape

(2, 3)

In [43]:
data.dtype

dtype('float64')

ndarray 생성하기

In [46]:
#1차원
ndarray 생성하기data = [ 6, 7.5, 8, 0, 1]
arr = np.array(data)
arr
#array는 다 같은 형태로, list는 다양한 데이터 다 들어갈 수 있음 

array([6. , 7.5, 8. , 0. , 1. ])

In [47]:
#2차원
data2d = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2d                       # 가로로 쭉나옴

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [48]:
arr2d = np.array(data2d)            # 행렬식으로 세로로 나옴

In [49]:
arr2d.ndim

2

In [50]:
arr2d.shape     #2행 4열

(2, 4)

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
#2차원 데이터
np.zeros((3, 6))        #np.zeros는 하나의 행렬만 받아들임 그래서 튜플로 묶음

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [55]:
np.zeros((2, 3, 2)).dtype      # 2층 3행 2열 (층, 행, 열)
#64비트짜리부동소수점   #float64가 기본

dtype('float64')

In [57]:
arr = np.zeros((2, 3, 2), dtype=np.int32)     #데이터타입 32비트 정수로 명시
arr.dtype

dtype('int32')

In [59]:
arr1 = np.zeros((2, 3))
arr2 = np.ones_like(arr1)
arr2.shape
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
arr3 = np.full((2, 3), 5)
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [62]:
arr4 = np.eye(3)
arr4      #단위행렬
#단위행렬은 어떨때 쓰나?
#곱셈에 대한 항등원: 곱하면 (처음과) 똑같이 나오는것

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])